project:
  type: website

website:
  title: "Stat 20 Staff Resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



