project:
  type: website

website:
  title: "Staff Resources"
  sidebar:
    title: "Staff Resources"
    logo: assets/stat20-hex-small.png
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: Agenda
        contents:
          - href: tutor-agenda.qmd
            text: Tutor Agenda
          - href: reader-agenda.qmd
            text: Reader Agenda
      - href: roles-and-expectations.qmd
        text: Roles & Expectations
        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



